# CMS STAGING CONFIGURATION

url: "https://stagingsite.edwardjensencms.com"
title: "Edward Jensen [LATEST STAGING]"

payload_graphql:
  url: "https://staging-tailscale.edwardjensencms.com/api/graphql"